/* Generated by gbrecomp from pokegold */
#include "pokegold_internal.h"
#include "gbrt.h"
#include <stdio.h>
#include <stdlib.h>

/* Bank dispatch - routes calls to the correct bank function */
void pokegold_dispatch_00(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokegold_dispatch_01(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokegold_dispatch_02(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokegold_dispatch_03(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokegold_dispatch_04(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokegold_dispatch_05(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokegold_dispatch_06(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokegold_dispatch_07(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokegold_dispatch_08(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokegold_dispatch_09(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokegold_dispatch_0a(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokegold_dispatch_0b(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokegold_dispatch_0c(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokegold_dispatch_0d(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokegold_dispatch_0e(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokegold_dispatch_0f(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokegold_dispatch_10(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokegold_dispatch_11(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokegold_dispatch_12(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokegold_dispatch_13(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokegold_dispatch_14(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokegold_dispatch_15(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokegold_dispatch_16(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokegold_dispatch_17(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokegold_dispatch_18(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokegold_dispatch_19(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokegold_dispatch_1a(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokegold_dispatch_1b(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokegold_dispatch_1c(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokegold_dispatch_1d(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokegold_dispatch_1e(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokegold_dispatch_1f(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokegold_dispatch_20(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokegold_dispatch_21(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokegold_dispatch_22(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokegold_dispatch_23(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokegold_dispatch_24(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokegold_dispatch_25(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokegold_dispatch_26(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokegold_dispatch_27(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokegold_dispatch_28(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokegold_dispatch_29(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokegold_dispatch_2a(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokegold_dispatch_2b(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokegold_dispatch_2c(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokegold_dispatch_2d(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokegold_dispatch_2e(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokegold_dispatch_2f(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokegold_dispatch_30(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokegold_dispatch_31(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokegold_dispatch_32(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokegold_dispatch_33(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokegold_dispatch_34(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokegold_dispatch_35(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokegold_dispatch_36(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokegold_dispatch_37(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokegold_dispatch_38(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokegold_dispatch_39(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokegold_dispatch_3a(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokegold_dispatch_3b(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokegold_dispatch_3c(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokegold_dispatch_3d(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokegold_dispatch_3e(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokegold_dispatch_3f(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokegold_dispatch_40(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokegold_dispatch_41(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokegold_dispatch_42(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokegold_dispatch_43(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokegold_dispatch_44(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokegold_dispatch_45(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokegold_dispatch_46(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokegold_dispatch_47(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokegold_dispatch_48(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokegold_dispatch_49(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokegold_dispatch_4a(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokegold_dispatch_4b(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokegold_dispatch_4c(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokegold_dispatch_4d(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokegold_dispatch_4e(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokegold_dispatch_4f(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokegold_dispatch_50(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokegold_dispatch_51(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokegold_dispatch_52(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokegold_dispatch_53(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokegold_dispatch_54(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokegold_dispatch_55(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokegold_dispatch_56(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokegold_dispatch_57(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokegold_dispatch_58(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokegold_dispatch_59(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokegold_dispatch_5a(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokegold_dispatch_5b(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokegold_dispatch_5c(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokegold_dispatch_5d(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokegold_dispatch_5e(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokegold_dispatch_5f(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokegold_dispatch_60(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokegold_dispatch_61(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokegold_dispatch_62(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokegold_dispatch_63(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokegold_dispatch_64(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokegold_dispatch_65(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokegold_dispatch_66(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokegold_dispatch_67(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokegold_dispatch_68(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokegold_dispatch_69(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokegold_dispatch_6a(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokegold_dispatch_6b(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokegold_dispatch_6c(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokegold_dispatch_6d(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokegold_dispatch_6e(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokegold_dispatch_6f(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokegold_dispatch_70(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokegold_dispatch_71(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokegold_dispatch_72(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokegold_dispatch_73(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokegold_dispatch_74(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokegold_dispatch_75(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokegold_dispatch_76(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokegold_dispatch_77(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokegold_dispatch_78(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokegold_dispatch_79(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokegold_dispatch_7a(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokegold_dispatch_7b(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokegold_dispatch_7c(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokegold_dispatch_7d(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokegold_dispatch_7e(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokegold_dispatch_7f(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokegold_dispatch_ff(GBContext* ctx, uint16_t addr, uint8_t bank);

static uint8_t pokegold__ram_overlay_0_matches(GBContext* ctx) {
    if (gb_read8(ctx, 0xff80) != 0x3e) return 0;
    if (gb_read8(ctx, 0xff81) != 0xc3) return 0;
    if (gb_read8(ctx, 0xff82) != 0xe0) return 0;
    if (gb_read8(ctx, 0xff83) != 0x46) return 0;
    if (gb_read8(ctx, 0xff84) != 0x3e) return 0;
    if (gb_read8(ctx, 0xff85) != 0x28) return 0;
    if (gb_read8(ctx, 0xff86) != 0x3d) return 0;
    if (gb_read8(ctx, 0xff87) != 0x20) return 0;
    if (gb_read8(ctx, 0xff88) != 0xfd) return 0;
    if (gb_read8(ctx, 0xff89) != 0xc9) return 0;
    return 1;
}

static uint8_t pokegold__try_dispatch_compiled_ram_overlay(GBContext* ctx, uint16_t addr, uint8_t bank) {
    if (addr >= 0xff80 && addr < 0xff8a) {
        if (!pokegold__ram_overlay_0_matches(ctx)) {
            return 0;
        }
        switch (addr) {
            case 0xff80:
                pokegold_dispatch_ff(ctx, addr, bank);
                return 1;
            case 0xff83:
                pokegold_dispatch_ff(ctx, addr, bank);
                return 1;
            default:
                return 0;
        }
    }
    return 0;
}

void pokegold__gb_dispatch(GBContext* ctx, uint16_t addr) {
    ctx->pc = addr;
    while (!ctx->stopped && !ctx->halted) {
        addr = ctx->pc;
        uint8_t bank = ctx->rom_bank;
        if (addr < 0x4000) bank = 0;
        if (gbrt_instruction_limit > 0 && gbrt_instruction_count >= gbrt_instruction_limit) {
            fprintf(stderr, "[LIMIT] Reached instruction limit %llu\n", (unsigned long long)gbrt_instruction_limit);
            exit(0);
        }
        gbrt_instruction_count++;
        gbrt_log_trace(ctx, bank, addr);
        if (gbrt_trace_enabled) {
            fprintf(stderr, "[TRACE] Dispatch 0x%04X (Bank %d)\n", addr, bank);
        }
        if (gbrt_try_execute_hram_stub(ctx, addr)) {
            if (ctx->single_step_mode) break;
            continue;
        }
        if (gbrt_try_execute_highmem_stub(ctx, addr)) {
            if (ctx->single_step_mode || ctx->stopped) break;
            continue;
        }
        if (gbrt_try_execute_ram_stub(ctx, addr)) {
            if (ctx->single_step_mode || ctx->stopped) break;
            continue;
        }
        if (pokegold__try_dispatch_compiled_ram_overlay(ctx, addr, bank)) {
            if (ctx->single_step_mode || ctx->stopped) break;
            continue;
        }
        if (addr >= 0xFF80 && addr <= 0xFFFE) {
            gbrt_note_dispatch_fallback(ctx, bank, addr);
            gb_interpret(ctx, addr);
            if (ctx->single_step_mode || ctx->stopped) break;
            continue;
        }
        switch (addr >> 8) {
            case 0x00: pokegold_dispatch_00(ctx, addr, bank); break;
            case 0x01: pokegold_dispatch_01(ctx, addr, bank); break;
            case 0x02: pokegold_dispatch_02(ctx, addr, bank); break;
            case 0x03: pokegold_dispatch_03(ctx, addr, bank); break;
            case 0x04: pokegold_dispatch_04(ctx, addr, bank); break;
            case 0x05: pokegold_dispatch_05(ctx, addr, bank); break;
            case 0x06: pokegold_dispatch_06(ctx, addr, bank); break;
            case 0x07: pokegold_dispatch_07(ctx, addr, bank); break;
            case 0x08: pokegold_dispatch_08(ctx, addr, bank); break;
            case 0x09: pokegold_dispatch_09(ctx, addr, bank); break;
            case 0x0a: pokegold_dispatch_0a(ctx, addr, bank); break;
            case 0x0b: pokegold_dispatch_0b(ctx, addr, bank); break;
            case 0x0c: pokegold_dispatch_0c(ctx, addr, bank); break;
            case 0x0d: pokegold_dispatch_0d(ctx, addr, bank); break;
            case 0x0e: pokegold_dispatch_0e(ctx, addr, bank); break;
            case 0x0f: pokegold_dispatch_0f(ctx, addr, bank); break;
            case 0x10: pokegold_dispatch_10(ctx, addr, bank); break;
            case 0x11: pokegold_dispatch_11(ctx, addr, bank); break;
            case 0x12: pokegold_dispatch_12(ctx, addr, bank); break;
            case 0x13: pokegold_dispatch_13(ctx, addr, bank); break;
            case 0x14: pokegold_dispatch_14(ctx, addr, bank); break;
            case 0x15: pokegold_dispatch_15(ctx, addr, bank); break;
            case 0x16: pokegold_dispatch_16(ctx, addr, bank); break;
            case 0x17: pokegold_dispatch_17(ctx, addr, bank); break;
            case 0x18: pokegold_dispatch_18(ctx, addr, bank); break;
            case 0x19: pokegold_dispatch_19(ctx, addr, bank); break;
            case 0x1a: pokegold_dispatch_1a(ctx, addr, bank); break;
            case 0x1b: pokegold_dispatch_1b(ctx, addr, bank); break;
            case 0x1c: pokegold_dispatch_1c(ctx, addr, bank); break;
            case 0x1d: pokegold_dispatch_1d(ctx, addr, bank); break;
            case 0x1e: pokegold_dispatch_1e(ctx, addr, bank); break;
            case 0x1f: pokegold_dispatch_1f(ctx, addr, bank); break;
            case 0x20: pokegold_dispatch_20(ctx, addr, bank); break;
            case 0x21: pokegold_dispatch_21(ctx, addr, bank); break;
            case 0x22: pokegold_dispatch_22(ctx, addr, bank); break;
            case 0x23: pokegold_dispatch_23(ctx, addr, bank); break;
            case 0x24: pokegold_dispatch_24(ctx, addr, bank); break;
            case 0x25: pokegold_dispatch_25(ctx, addr, bank); break;
            case 0x26: pokegold_dispatch_26(ctx, addr, bank); break;
            case 0x27: pokegold_dispatch_27(ctx, addr, bank); break;
            case 0x28: pokegold_dispatch_28(ctx, addr, bank); break;
            case 0x29: pokegold_dispatch_29(ctx, addr, bank); break;
            case 0x2a: pokegold_dispatch_2a(ctx, addr, bank); break;
            case 0x2b: pokegold_dispatch_2b(ctx, addr, bank); break;
            case 0x2c: pokegold_dispatch_2c(ctx, addr, bank); break;
            case 0x2d: pokegold_dispatch_2d(ctx, addr, bank); break;
            case 0x2e: pokegold_dispatch_2e(ctx, addr, bank); break;
            case 0x2f: pokegold_dispatch_2f(ctx, addr, bank); break;
            case 0x30: pokegold_dispatch_30(ctx, addr, bank); break;
            case 0x31: pokegold_dispatch_31(ctx, addr, bank); break;
            case 0x32: pokegold_dispatch_32(ctx, addr, bank); break;
            case 0x33: pokegold_dispatch_33(ctx, addr, bank); break;
            case 0x34: pokegold_dispatch_34(ctx, addr, bank); break;
            case 0x35: pokegold_dispatch_35(ctx, addr, bank); break;
            case 0x36: pokegold_dispatch_36(ctx, addr, bank); break;
            case 0x37: pokegold_dispatch_37(ctx, addr, bank); break;
            case 0x38: pokegold_dispatch_38(ctx, addr, bank); break;
            case 0x39: pokegold_dispatch_39(ctx, addr, bank); break;
            case 0x3a: pokegold_dispatch_3a(ctx, addr, bank); break;
            case 0x3b: pokegold_dispatch_3b(ctx, addr, bank); break;
            case 0x3c: pokegold_dispatch_3c(ctx, addr, bank); break;
            case 0x3d: pokegold_dispatch_3d(ctx, addr, bank); break;
            case 0x3e: pokegold_dispatch_3e(ctx, addr, bank); break;
            case 0x3f: pokegold_dispatch_3f(ctx, addr, bank); break;
            case 0x40: pokegold_dispatch_40(ctx, addr, bank); break;
            case 0x41: pokegold_dispatch_41(ctx, addr, bank); break;
            case 0x42: pokegold_dispatch_42(ctx, addr, bank); break;
            case 0x43: pokegold_dispatch_43(ctx, addr, bank); break;
            case 0x44: pokegold_dispatch_44(ctx, addr, bank); break;
            case 0x45: pokegold_dispatch_45(ctx, addr, bank); break;
            case 0x46: pokegold_dispatch_46(ctx, addr, bank); break;
            case 0x47: pokegold_dispatch_47(ctx, addr, bank); break;
            case 0x48: pokegold_dispatch_48(ctx, addr, bank); break;
            case 0x49: pokegold_dispatch_49(ctx, addr, bank); break;
            case 0x4a: pokegold_dispatch_4a(ctx, addr, bank); break;
            case 0x4b: pokegold_dispatch_4b(ctx, addr, bank); break;
            case 0x4c: pokegold_dispatch_4c(ctx, addr, bank); break;
            case 0x4d: pokegold_dispatch_4d(ctx, addr, bank); break;
            case 0x4e: pokegold_dispatch_4e(ctx, addr, bank); break;
            case 0x4f: pokegold_dispatch_4f(ctx, addr, bank); break;
            case 0x50: pokegold_dispatch_50(ctx, addr, bank); break;
            case 0x51: pokegold_dispatch_51(ctx, addr, bank); break;
            case 0x52: pokegold_dispatch_52(ctx, addr, bank); break;
            case 0x53: pokegold_dispatch_53(ctx, addr, bank); break;
            case 0x54: pokegold_dispatch_54(ctx, addr, bank); break;
            case 0x55: pokegold_dispatch_55(ctx, addr, bank); break;
            case 0x56: pokegold_dispatch_56(ctx, addr, bank); break;
            case 0x57: pokegold_dispatch_57(ctx, addr, bank); break;
            case 0x58: pokegold_dispatch_58(ctx, addr, bank); break;
            case 0x59: pokegold_dispatch_59(ctx, addr, bank); break;
            case 0x5a: pokegold_dispatch_5a(ctx, addr, bank); break;
            case 0x5b: pokegold_dispatch_5b(ctx, addr, bank); break;
            case 0x5c: pokegold_dispatch_5c(ctx, addr, bank); break;
            case 0x5d: pokegold_dispatch_5d(ctx, addr, bank); break;
            case 0x5e: pokegold_dispatch_5e(ctx, addr, bank); break;
            case 0x5f: pokegold_dispatch_5f(ctx, addr, bank); break;
            case 0x60: pokegold_dispatch_60(ctx, addr, bank); break;
            case 0x61: pokegold_dispatch_61(ctx, addr, bank); break;
            case 0x62: pokegold_dispatch_62(ctx, addr, bank); break;
            case 0x63: pokegold_dispatch_63(ctx, addr, bank); break;
            case 0x64: pokegold_dispatch_64(ctx, addr, bank); break;
            case 0x65: pokegold_dispatch_65(ctx, addr, bank); break;
            case 0x66: pokegold_dispatch_66(ctx, addr, bank); break;
            case 0x67: pokegold_dispatch_67(ctx, addr, bank); break;
            case 0x68: pokegold_dispatch_68(ctx, addr, bank); break;
            case 0x69: pokegold_dispatch_69(ctx, addr, bank); break;
            case 0x6a: pokegold_dispatch_6a(ctx, addr, bank); break;
            case 0x6b: pokegold_dispatch_6b(ctx, addr, bank); break;
            case 0x6c: pokegold_dispatch_6c(ctx, addr, bank); break;
            case 0x6d: pokegold_dispatch_6d(ctx, addr, bank); break;
            case 0x6e: pokegold_dispatch_6e(ctx, addr, bank); break;
            case 0x6f: pokegold_dispatch_6f(ctx, addr, bank); break;
            case 0x70: pokegold_dispatch_70(ctx, addr, bank); break;
            case 0x71: pokegold_dispatch_71(ctx, addr, bank); break;
            case 0x72: pokegold_dispatch_72(ctx, addr, bank); break;
            case 0x73: pokegold_dispatch_73(ctx, addr, bank); break;
            case 0x74: pokegold_dispatch_74(ctx, addr, bank); break;
            case 0x75: pokegold_dispatch_75(ctx, addr, bank); break;
            case 0x76: pokegold_dispatch_76(ctx, addr, bank); break;
            case 0x77: pokegold_dispatch_77(ctx, addr, bank); break;
            case 0x78: pokegold_dispatch_78(ctx, addr, bank); break;
            case 0x79: pokegold_dispatch_79(ctx, addr, bank); break;
            case 0x7a: pokegold_dispatch_7a(ctx, addr, bank); break;
            case 0x7b: pokegold_dispatch_7b(ctx, addr, bank); break;
            case 0x7c: pokegold_dispatch_7c(ctx, addr, bank); break;
            case 0x7d: pokegold_dispatch_7d(ctx, addr, bank); break;
            case 0x7e: pokegold_dispatch_7e(ctx, addr, bank); break;
            case 0x7f: pokegold_dispatch_7f(ctx, addr, bank); break;
            case 0xff: pokegold_dispatch_ff(ctx, addr, bank); break;
            default: gbrt_note_dispatch_fallback(ctx, bank, addr); gb_interpret(ctx, addr); break;
        }
        if (ctx->single_step_mode) break;
    }
}

void pokegold__gb_dispatch_call(GBContext* ctx, uint16_t addr) {
    pokegold__gb_dispatch(ctx, addr);
}

/* Extern reference to ROM data */
extern uint8_t pokegold__rom_data[];
extern const size_t pokegold__rom_size;

const GBConfig* pokegold_default_config(void) {
    static const GBConfig config = {
        .model = GB_MODEL_CGB,
        .cgb_compatibility_mode = false,
        .cartridge_supports_cgb = true,
        .cartridge_requires_cgb = false,
        .enable_bootrom = false,
        .enable_audio = true,
        .enable_serial = true,
        .speed_percent = 100,
    };
    return &config;
}

void pokegold_init(GBContext* ctx) {
    /* Load ROM data into context */
    gb_context_load_rom(ctx, pokegold__rom_data, pokegold__rom_size);
    /* Set MBC type from header */
    ctx->mbc_type = pokegold__rom_data[0x147];
    gb_context_reset(ctx, true);
}

void pokegold_run(GBContext* ctx) {
    // Start the trampoline loop - execution will stay here until stopped
    pokegold__gb_dispatch(ctx, ctx->pc);
}
