/* Generated by gbrecomp */
#ifndef pokegold_H
#define pokegold_H

#include "gbrt.h"

const GBConfig* pokegold_default_config(void);
void pokegold_run(GBContext* ctx);
void pokegold_init(GBContext* ctx);
int pokegold_main(int argc, char* argv[]);

#endif
